# Composer stores all downloaded packages in the vendor/ directory.
cache:
  paths:
    - vendor/

before_script:
  - bash tests/ci/docker_install.sh > /dev/null
  # Get composer
  - curl -sS https://getcomposer.org/installer | php
  # Set the package.studio deploy token from the environment
  - php composer.phar config http-basic.api.package.studio x-deploy-token $PACKAGE_STUDIO_DEPLOY_TOKEN
  # Install composer dependencies
  - php composer.phar install

# We test PHP7.0
test:7.0:
  image: php:7.0
  script:
    - ./vendor/bin/phpunit --configuration tests/phpunit.xml
