dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit -c tests/phpunit.xml

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache